name: test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
            uses: actions/checkout@v4
            - name: Node setup
            uses: actions/setup-node@v4
            with:
                node_version: 20
            -name: Install dep
            uses: npm ci
